//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtobusFirması
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biletler
    {
        public int YolcuID { get; set; }
        public Nullable<int> SeferID { get; set; }
        public Nullable<System.DateTime> IslemZamani { get; set; }
        public Nullable<int> KoltukNo { get; set; }
        public string YolcuCinsiyet { get; set; }
        public string YolcuAd { get; set; }
        public string YolcuSoyad { get; set; }
        public string Ucret { get; set; }
    
        public virtual Musteriler Musteriler { get; set; }
        public virtual Seferler Seferler { get; set; }
    }
}
