//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtobusFirması
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OtobusEntities : DbContext
    {
        public OtobusEntities()
            : base("name=OtobusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Biletler> Biletlers { get; set; }
        public virtual DbSet<Calisanlar> Calisanlars { get; set; }
        public virtual DbSet<CalisanTipleri> CalisanTipleris { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Markalar> Markalars { get; set; }
        public virtual DbSet<Musteriler> Musterilers { get; set; }
        public virtual DbSet<Otobusler> Otobuslers { get; set; }
        public virtual DbSet<Seferler> Seferlers { get; set; }
        public virtual DbSet<Sehirler> Sehirlers { get; set; }
    }
}
